{"name": "Проверка ответа на запрос аутентификации с неверным паролем", "status": "passed", "start": 1725975016772, "stop": 1725975017194, "uuid": "d3b0d4d6-040a-4c46-adbe-3fd9e5cb3969", "historyId": "7b59ea21293aa51d8fb438826b986f6c", "testCaseId": "7b59ea21293aa51d8fb438826b986f6c", "fullName": "tests.test_authentication.TestAuthentication#test_auth_with_wrong_passwd_expected_error", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_authentication"}, {"name": "subSuite", "value": "TestAuthentication"}, {"name": "host", "value": "DESKTOP-82VEM3U"}, {"name": "thread", "value": "13288-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_authentication"}]}